# -*- coding: utf-8 -*-
"""LVADSUSR75_barathvaraj_lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4-oDDlkjddVuvdp1QGnprsKRVPcXZQi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest

df=pd.read_csv("/content/drive/MyDrive/pred_analysis_datasets/finalassess/social_network.csv")
df.head()

sns.boxplot(df[['login_activity','posting_activity','social_connections','suspicious_activity']])
plt.show()

cols=df[['login_activity','posting_activity','social_connections']]

iso=IsolationForest(contamination=0.3)
outliers=iso.fit_predict(cols)
df_outliers=df.iloc[np.where(outliers==-1)]
print("Anomaly Values: ", df_outliers)