# -*- coding: utf-8 -*-
"""LVADSUSR75-Barathvaraj-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uvbcH-CV23zMAbwVvqOTzWp-YyR0hJMO
"""

#1
import numpy as np
import pandas as pd
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255],[255,255,0],[255,0,255],[0,255,255],[127,127,127],[200,200,200],[50,50,50]]])

df_1=pd.DataFrame(rgb_image.reshape(9,3))
df_1.columns=['R','G','B']
sum_df_1=df_1['R']+df_1['G']+df_1['B']
print(sum_df_1)

#2
from sklearn.preprocessing import MinMaxScaler
array_2=np.array([[1.5,67,23],[1.8,77,33],[1.6,57,43],[1.6,70,29],[1.9,89,45]])
df_2=pd.DataFrame(array_2)
df_2.columns=['Height','Weight','Age']

def transform_arr_2(cols):
  scaler=MinMaxScaler()
  cols=scaler.fit_transform(cols)
  return cols

df_2[['Weight','Age']]=transform_arr_2(df_2[['Weight','Age']])
print(df_2.describe())

#3

array_3=np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]]])
array_3=array_3.flatten('C')
array_3=array_2.reshape(-1,1)
print(array_3)

#4

array_4=np.array([["Athlete 1",1,50],["Athlete 1",2,60],["Athlete 2",1,45],["Athlete 2",2,40]])
df_4=pd.DataFrame(array_4,columns=['Athlete_name','Game_no','Scores'])
df_4=df_4.groupby(['Athlete_name','Game_no'])['Scores'].aggregate('sum')
print(df_4)

#5

array_5=np.array([['stud 1','sub 1',92],['stud 2','sub 1',87],['stud 1','sub 2',78],['stud 2','sub 2',91],['stud 3','sub 3',-1],['stud 2','sub 3',71],['stud 1','sub 3',70]])
df_5=pd.DataFrame(array_5,columns=['Student_name','Subject_name','Marks'])
df_5['Marks']=df_5['Marks'].replace(-1,np.nan)
print(df_5)
df_grouped_5=df_5.groupby('Student_name')['Marks'].aggregate('mean')
print(df_grouped_5)

#6

data_7={'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],'Age':[25,30,35,40,45,50,55],'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']}
df_7=pd.DataFrame(data_7)
under_45=df_7[df_7['Age']<45]
not_hr=under_45[under_45['Department']!='HR']
lst=not_hr[['Name','City']].to_numpy()
print(lst)

#7

data_7={'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],'Age':[25,30,35,40,45,50,55],'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']}
df_7=pd.DataFrame(data_7)
under_45=df_7[df_7['Age']<45]
not_hr=under_45[under_45['Department']!='HR']
lst=not_hr[['Name','City']].to_numpy()
print(lst)

#8

df_8=pd.read_csv("/content/drive/MyDrive/assess_datasets/q8_data.csv")
fruit_cat=df_8[df_8['Category']=='Fruit']
avg_price_8=df_8['Price'].mean()
above_avg=fruit_cat[fruit_cat['Price']>avg_price_8]
not_promotion=above_avg[above_avg['Promotion']=='False']
print(not_promotion)

#9

df_emp_9=pd.read_csv("/content/drive/MyDrive/assess_datasets/q9_employee_data.csv")
df_proj_9=pd.read_csv("/content/drive/MyDrive/assess_datasets/q9_project_data.csv")

df_9=pd.merge(df_emp_9,df_proj_9,on='Employee', how='left')
df_9.fillna("To be allocated",inplace=True)
print(df_9)

#10
data_10={'Department':['Electronics','Electronics','Clothing','Clothing','Home','Goods'],'Sales'}
df_10=pd.DataFrame(data_10)
df_10=df_10.groupby('Salesperson')['Sales'].aggregate('mean')
df_10=df_10.sort_values(df_10['Sales'],ascending=False)